[package]
name = "hashable_weak"
version = "0.1.0"
edition = "2021"
license = "BSD-3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
